22_rails_api/taco_tracker/config/routes.rb
Rails.application.routes.draw do
  resources :taco_ingredients
  resources :ingredients
  resources :tacos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

22_rails_api/taco_tracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

22_rails_api/taco_tracker/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :taco_ingredients
  has_many :tacos, through: :taco_ingredients
end

22_rails_api/taco_tracker/app/models/taco.rb
class Taco < ApplicationRecord
  has_many :taco_ingredients
  has_many :ingredients, through: :taco_ingredients
  enum shell: [ :hard, :soft, :dorito, :pita ]

  # def ingredient_names
  #   self.ingredients.map(&:name)
  # end
end

22_rails_api/taco_tracker/app/models/taco_ingredient.rb
class TacoIngredient < ApplicationRecord
  belongs_to :taco
  belongs_to :ingredient
end

22_rails_api/taco_tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

22_rails_api/taco_tracker/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

22_rails_api/taco_tracker/app/controllers/taco_ingredients_controller.rb
class TacoIngredientsController < ApplicationController
  before_action :set_taco_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /taco_ingredients
  # GET /taco_ingredients.json
  def index
    @taco_ingredients = TacoIngredient.all
  end

  # GET /taco_ingredients/1
  # GET /taco_ingredients/1.json
  def show
  end

  # GET /taco_ingredients/new
  def new
    @taco_ingredient = TacoIngredient.new
  end

  # GET /taco_ingredients/1/edit
  def edit
  end

  # POST /taco_ingredients
  # POST /taco_ingredients.json
  def create
    @taco_ingredient = TacoIngredient.new(taco_ingredient_params)

    respond_to do |format|
      if @taco_ingredient.save
        format.html { redirect_to @taco_ingredient, notice: 'Taco ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @taco_ingredient }
      else
        format.html { render :new }
        format.json { render json: @taco_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taco_ingredients/1
  # PATCH/PUT /taco_ingredients/1.json
  def update
    respond_to do |format|
      if @taco_ingredient.update(taco_ingredient_params)
        format.html { redirect_to @taco_ingredient, notice: 'Taco ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @taco_ingredient }
      else
        format.html { render :edit }
        format.json { render json: @taco_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taco_ingredients/1
  # DELETE /taco_ingredients/1.json
  def destroy
    @taco_ingredient.destroy
    respond_to do |format|
      format.html { redirect_to taco_ingredients_url, notice: 'Taco ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taco_ingredient
      @taco_ingredient = TacoIngredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taco_ingredient_params
      params.require(:taco_ingredient).permit(:taco_id, :ingredient_id)
    end
end

22_rails_api/taco_tracker/app/controllers/tacos_controller.rb
class TacosController < ApplicationController
  before_action :set_taco, only: [:show, :edit, :update, :destroy]

  # GET /tacos
  # GET /tacos.json
  def index
    @tacos = Taco.all
    render json: @tacos, each_serializer: TacoLiteSerializer
  end

  # GET /tacos/1
  # GET /tacos/1.json
  def show
    render json: @taco
  end

  # POST /tacos
  # POST /tacos.json
  def create
    @taco = Taco.new(taco_params)

    if @taco.save
      # format.html { redirect_to @taco, notice: 'Taco was successfully created.' }
      # format.json { render :show, status: :created, location: @taco }
      render json: @taco, status: :created, location: @taco
    else
      # format.html { render :new }
      # format.json { render json: @taco.errors, status: :unprocessable_entity }
      render json: @taco.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tacos/1
  # PATCH/PUT /tacos/1.json
  # def update
  #   respond_to do |format|
  #     if @taco.update(taco_params)
  #       format.html { redirect_to @taco, notice: 'Taco was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @taco }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @taco.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /tacos/1
  # # DELETE /tacos/1.json
  # def destroy
  #   @taco.destroy
  #   respond_to do |format|
  #     format.html { redirect_to tacos_url, notice: 'Taco was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taco
      @taco = Taco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taco_params
      t_params = params.require(:taco).permit(:name, :shell, :spiciness)
      # t_params[:shell] = t_params[:shell].to_i
      # t_params
    end
end

22_rails_api/taco_tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

22_rails_api/taco_tracker/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

22_rails_api/taco_tracker/app/helpers/taco_ingredients_helper.rb
module TacoIngredientsHelper
end

22_rails_api/taco_tracker/app/helpers/tacos_helper.rb
module TacosHelper
end

22_rails_api/taco_tracker/app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

22_rails_api/taco_tracker/app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

22_rails_api/taco_tracker/app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

22_rails_api/taco_tracker/app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

22_rails_api/taco_tracker/app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

22_rails_api/taco_tracker/app/views/taco_ingredients/_form.html.erb
<%= form_with(model: taco_ingredient, local: true) do |form| %>
  <% if taco_ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(taco_ingredient.errors.count, "error") %> prohibited this taco_ingredient from being saved:</h2>

      <ul>
      <% taco_ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :taco_id %>
    <%= form.number_field :taco_id %>
  </div>

  <div class="field">
    <%= form.label :ingredient_id %>
    <%= form.number_field :ingredient_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

22_rails_api/taco_tracker/app/views/taco_ingredients/edit.html.erb
<h1>Editing Taco Ingredient</h1>

<%= render 'form', taco_ingredient: @taco_ingredient %>

<%= link_to 'Show', @taco_ingredient %> |
<%= link_to 'Back', taco_ingredients_path %>

22_rails_api/taco_tracker/app/views/taco_ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Taco Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Taco</th>
      <th>Ingredient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taco_ingredients.each do |taco_ingredient| %>
      <tr>
        <td><%= taco_ingredient.taco_id %></td>
        <td><%= taco_ingredient.ingredient_id %></td>
        <td><%= link_to 'Show', taco_ingredient %></td>
        <td><%= link_to 'Edit', edit_taco_ingredient_path(taco_ingredient) %></td>
        <td><%= link_to 'Destroy', taco_ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taco Ingredient', new_taco_ingredient_path %>

22_rails_api/taco_tracker/app/views/taco_ingredients/new.html.erb
<h1>New Taco Ingredient</h1>

<%= render 'form', taco_ingredient: @taco_ingredient %>

<%= link_to 'Back', taco_ingredients_path %>

22_rails_api/taco_tracker/app/views/taco_ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Taco:</strong>
  <%= @taco_ingredient.taco_id %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @taco_ingredient.ingredient_id %>
</p>

<%= link_to 'Edit', edit_taco_ingredient_path(@taco_ingredient) %> |
<%= link_to 'Back', taco_ingredients_path %>