13_rails_auth/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resources :repositories, only: [:index]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  match '*missing' => redirect('/404')
end

13_rails_auth/app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :user
end

13_rails_auth/app/models/user.rb
class User < ApplicationRecord
  has_many :repositories
  has_secure_password
end

13_rails_auth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    else
    end
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

  def logged_in?
    !!current_user
  end
end

13_rails_auth/app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :authorized

  def index
      @repositories = current_user.repositories
  end

end

13_rails_auth/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # To the login form
  def new
  end

  # This is going to go through the
  # authentication process
  def create
    # binding.pry
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session.delete :user_id
    redirect_to login_path
  end
end

13_rails_auth/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Sign up Process - new, create, show

  def new
    @user = User.new
  end

  def create
    # binding.pry
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

13_rails_auth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <h2>GitBetter™</h2>
      <% if logged_in? %>
        <%= button_to "Logout", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Login", login_path %> / <%= link_to "Sign up", signup_path %>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

13_rails_auth/app/views/repositories/index.html.erb
<% @repositories.each do |repo| %>
  <li><%= repo.name %> (made by <%= repo.user.username %>) - <%= repo.description %></li>
<% end %>

13_rails_auth/app/views/users/new.html.erb
<h2>Sign up for GitBetter™</h2>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>

  <%= f.submit "Sign up!" %>
<% end %>

13_rails_auth/app/views/users/show.html.erb
<%= @user.username %>